baseURL = 'https://git.legaragenumerique.fr/GARAGENUM/LTQF'
languageCode = 'en-us'
title = 'LTQF'
buildFuture= true

[params]
    description = "Un site de théatre."
    favicon = "/favicon.png"
    logo = "ltqf.png"
    logoHome = "logo_home.jpg" 
    debug = true
    currentLayout = ""
    Copyright = "LTQF avec Le Garage Numérique"
    CopyrightHost = "https://www.legaragenumerique.fr"

[menu]
[[menu.main]]
    name = "La compagnie"
    url = "/compagnie"
    weight = 1

[[menu.main]]
    name = "Spectacles"
    url = "/spectacles"
    weight = 2

[[menu.main]]
    name = "Actions culturelles"
    url = "/actions_culturelles"
    weight = 3

[[menu.main]]
    name = "Presse"
    url = "/presse"
    weight = 5

[[menu.main]]
    name = "Actualités"
    url = "/actualites"
    weight = 6

[[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 7